### ISSUE TITLE
missing logger name

### ISSUE THREAD

**Issue by blalor** [logstash/log4j-jsonevent-layout#12]
Is there a reason the logger name isn't included in the output?  I'm getting log entries like

```
{"@fields":{"level":"INFO","mdc":{},"file":"?","class":"?","line_number":"?","method":"?"},"@timestamp":"2013-04-04T23:01:37.269-04:00","@message":"starting","@source_host":"unknown-host"}
```

Compare that to 

```
2013-04-04 23:01:37,269 [New I/O  worker #4] INFO  com.autosportlabs.rc_live.stream_recorder.RecorderVerticle - starting
```

The location info is cool when enabled, but the logger is a very important piece of information.  It should be trivial to add, but I wanted to make sure I'm not missing something.

**Comment by lusis** [comment]
Weird. Ill try and get your merge in this weekend. It's likely an oversight on my part.
