### ISSUE TITLE
timestamp?

### ISSUE THREAD

**Issue by jordansissel** [logstash/log4j-jsonevent-layout#2]
In the readme, I see:

```
{"@fields":{"timestamp":1354696445564,"level":"INFO","mdc":{},"file":"Server.java","class":"org.eclipse.jetty.server.Server","line_number":"268","method":"doStart"},"@message":"jetty-8.1.7.v20120910","@source_host":"vagrant.vm"}
```

So @fields -> timestamp -> unix epoch in millis.

Why not @timestamp -> ISO8601 time?

**Comment by lusis** [comment]
Good point. As we discussed on IRC, @type should probably be there as well. I'll noodle on this.

**Comment by pyr** [comment]
see #3 for a proposition

**Comment by pyr** [comment]
this has been merged, closing
