### ISSUE TITLE
[Suggestion] Rename JSONEventLayout -> JSONEventLayoutV0 and JSONEventLayoutV1 -> JSONEventLayout

### ISSUE THREAD

**Issue by Spredzy** [logstash/log4j-jsonevent-layout#21]
I would like to suggest to change the name of the current classes as follow
- JSONEventLayout -> JSONEventLayoutV0
- JSONEventLayoutV1 -> JSONEventLayout

For every new comer to Logstash, they will be using v1 without even knowing that there is/was V0 and V1. Right now if you want to use JSONEventLayout with V1 you need to specify it `net.logstash.log4j.JSONEventLayoutV1`

I think it should be the other way around, people wanting to keep legacy version should specifty it, but JSONEventLayout will always point to up-to-date Logstash version.

So if there is at a latter point a v2, we will have JSONEventLayoutV0, JSONEventLayoutV1, JSONEventLayout.

I thought it was something that is worth debating before submitting a PR

**Comment by lusis** [comment]
This totally makes sense. I was largely waiting for the new format to get merged upstream (and I also hate breaking existing installs) however now is the time.

If you don't want to make a PR, I can totally do this myself.

**Comment by lusis** [comment]
See comments on #23 . I went a slightly different route in dfbdfcdcd9a4a4e95fbb6efcf396e68b5be28626
