### ISSUE TITLE
ERROR A "net.logstash.log4j.JSONEventLayoutV1" object is not assignable to a "org.apache.log4j.Layout" variable

### ISSUE THREAD

**Issue by Zordrak** [logstash/log4j-jsonevent-layout#25]
This may be my fault, as I'm trying to navigate blind - but I'm using Spredzy's master, which I'm hoping will get pulled into logstash but getting a rather bizarre result.

My logs are happily coming out in JSON format as expected, but I'm also getting this in my Catalina.out:

log4j:ERROR A "net.logstash.log4j.JSONEventLayoutV1" object is not assignable to a "org.apache.log4j.Layout" variable.
log4j:ERROR The class "org.apache.log4j.Layout" was loaded by 
log4j:ERROR [WebappClassLoader
  delegate: false
  repositories:
    /WEB-INF/classes/
----------> Parent Classloader:
org.apache.catalina.loader.StandardClassLoader@66650e56
] whereas object of type 
log4j:ERROR "net.logstash.log4j.JSONEventLayoutV1" was loaded by [org.apache.catalina.loader.StandardClassLoader@66650e56].
log4j:ERROR No layout set for the appender named [CATALINA].

My config/versions is as per http://blog.tpa.me.uk/2013/10/17/logstash-tomcat6-log4j-on-centos-6/

Really unsure if this is me or the code..

**Comment by Spredzy** [comment]
@Zordrak Could you pull again from my master and try it again.

The branch I am making the PR against was renaming_classes, I haven't noticed that master was unfortuantely in an unstable state. It has been fixed and I merged renaming_classes to my master. You should be good to go, let me know if that's not the case.

**Comment by Zordrak** [comment]
Thanks Spredzy. I will rebuild the master (have put it into my Jenkins) - though I must report this was my fault not yours - very sorry about that. The message is an issue regarding log4j being loaded by both the StandardClassLoader and the WebappClassLoader causing a library collision. I'm having to work around it by removing log4j from the webapps which the dev guys aren't too happy about, but nonetheless I'm closer to a solution :-)

**Comment by veetow** [comment]
I think this is an actual issue. I can't get the logger to function unless all log4j jar files are removed from the class path entirely. Only the jsonevent layout jar must exist on the class path.
