### ISSUE TITLE
Best way sending JSON events over the network to logstash

### ISSUE THREAD

**Issue by joerno** [logstash/log4j-jsonevent-layout#38]
Hello,
just a question, do you now a way to send the JSON events over the network to logstash? I don't have access to the filesystem. I tried using the a SocketAppender with Logstash log4j-input, but I miss some fields this way. 
The SocketAppender doesn't supports layouts, so I dont see a way to use it with this layout here.

Thanks and regards

Joern

**Comment by lusis** [comment]
@joerno I'm so sorry I've been lax in responding. Unfortunately using the native log4j appenders, I can't think of one. You might be able to send these events via syslog. Otherwise you'll need to actually use somethind like the rabbitmq appender or redis appender combined with this layout.
