### ISSUE TITLE
Error when implementing

### ISSUE THREAD

**Issue by electrical** [logstash/log4j-jsonevent-layout#4]
Hiya,

I've tried to implement it in my log4j.xml config and i'm getting this error:

log4j:ERROR Could not create the Layout. Reported error follows.
java.lang.ClassCastException: net.logstash.log4j.JSONEventLayout cannot be cast to org.apache.log4j.Layout

Any idea?

**Comment by lusis** [comment]
@electrical sorry I missed this. Been heads down with work stuff. I'm going to take a look as soon as I can. Doing some cleanup now.

**Comment by electrical** [comment]
Should close this now as its been solved.
