### ISSUE TITLE
Access fields in MDC Sub-Object 

### ISSUE THREAD

**Issue by mcbain** [logstash/log4j-jsonevent-layout#42]
We use the Log4J MDC Feature and the JSON contains a sub object mdc with certain values. 
We need to make them top-level. 
How to do this? 
Dot based referencing from e.g. rename does not work 
e.g. rename => ["mdc.foo", "foo"]

**Comment by jordansissel** [comment]
For clarity, 'dot based referencing' isn't a feature logstash has. Logstash calls this a 'field reference' and uses [bracket][notation] for referencing nested fields. Example: `rename => [ "[mdc][foo]", "foo" ]`

**Comment by mcbain** [comment]
Thank you for quick response.
Since the MDC is a dynamic object, its possible to make the fields top-level without knowing their names ?
