### ISSUE TITLE
Add new team for contributors to this repo

### ISSUE THREAD

**Issue by lusis** [logstash/log4j-jsonevent-layout#7]
@jordansissel no rush but is it possible for us to create a team for this repo (like reponame-contributors or something) and add @pyr and @StFS to it? Again no rush just want to get the other contributors in here so I'm not the only person maintaining PRs ;)

**Comment by jordansissel** [comment]
Yeah hold on let me computer that.

**Comment by jordansissel** [comment]
Done.

https://github.com/organizations/logstash/teams/348417 - assuming anyone but me can see that.

**Comment by lusis** [comment]
I can't see it but I'll assume that @pyr and @StFS will have different visibility. You could also just make me god on logstash org ;) (jk)

**Comment by jordansissel** [comment]
I thought for sure you were already.

This internet thing. How does it work?

**Comment by StFS** [comment]
I haven't used GitHub all that much but I can see this team and I seem to have some sort of access now to the repository. Thanks for the trust :-)

However, we're probably moving over to using logback instead of log4j so I don't know how involved I'll be here.
