### ISSUE TITLE
Performance drop

### ISSUE THREAD

**Issue by Spredzy** [logstash/log4j-jsonevent-layout#8]
Not sure how I can provide useful information for this issue, but when I am using `org.apache.log4j.PatternLayout` the application is just fluid, checking at the log everything goes pretty fast. When I set this to `net.logstash.log4j.JSONEventLayout` it becomes unusable, logs get displayed but really slow, one at a time.

Any idea of why ?

Those are the maven version information with which I built the jar file

```
Apache Maven 2.2.1 (r801777; 2009-08-06 12:16:01-0700)
Java version: 1.6.0_24
Java home: /usr/lib/jvm/java-1.6.0-openjdk-1.6.0.0.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux" version: "2.6.32-220.23.1.el6.x86_64" arch: "amd64" Family: "unix"
```

Let me know if I can provide any further useful information

**Comment by StFS** [comment]
Are you sure this is an "actual" performance drop? Can you measure the execution time of your application somehow using the standard pattern layout vs. json_event layout?

It's just a thought but this might be a buffering issue, that json_event is just not flushing the buffers as frequently. So I'd suggest that you measure whether the actual performance of your system is being affected or whether it's just a notable delay in the log lines appearing.

**Comment by Spredzy** [comment]
After spending time looking for the reason it looks that way

Under an heavy load of log, using JSONEventLayout made my application slower than standard PatternLayout - not just the log displaying but the application also.

Once I removed all the log I had put in (it was really verbose), the application is just going well and JSONEventLayout is not a problem at all.

Not sure if it helps but this is what I could verify

**Comment by pyr** [comment]
an interesting approach would be to have those logs at DEBUG level, run the
app at that level and during slow down run jstack on your process and
attach the output here or on a gist.

**Comment by StFS** [comment]
Can you check memory usage? Is it growing with JSONEventLayout more than with the regular pattern layout?

You can also try to turn off the location info (construct the layout with JSONEventLayout(false)). I know that does improve performance quite a bit (my tests showed that 100.000 log messages in a tight loop took around 4000 ms with it turned on but around 700 with it turned off). This was added recently and I'm not sure whether that version is in Maven Central or not but it is in the latest version of the code here on GitHub (see https://github.com/logstash/log4j-jsonevent-layout/pull/5).

-Stefan

**Comment by Spredzy** [comment]
@pyr there you go for the jstack output https://gist.github.com/Spredzy/5110604

**Comment by Spredzy** [comment]
@StFS I am using the Github version, so location is already set to false

**Comment by StFS** [comment]
By default, locationInfo is set to true (if you use the default constructor). You _have to call it with false_ to turn off location info (just to be clear).

That said, I added to that ignored test case to compare the times of 100.000 logging statements between JSONEventLayout with locationInfo turned on and off and PatternLayout with and without location info in the pattern. Here are the results and the answer is basically "yes", the JSONEventLayout is significantly slower (times are in milliseconds):

JSONEventLayout (locationInfo: true): 4927
JSONEventLayout (locationInfo: false): 513
PatternLayout (%-5p [%t]: %m%n): 77
PatternLayout (%-5p %l [%t]: %m%n): 3379

**Comment by StFS** [comment]
Maybe it might be worth it to try some other JSON parser. Perhaps the net.minidev.json package isn't the fastest one around?

**Comment by Spredzy** [comment]
In case it can help fur further research https://github.com/eishay/jvm-serializers/wiki

**Comment by lusis** [comment]
I'm not opposed to switching JSON impls and I'll freely admit Java isn't my strong spot so there are likely logic related improvements that can be made.

I would also make sure that if you're logging to a file that you're using async appender.

We had so much blocking on file appenders with just the standard layout that we only log error to file and then everything else over network to logstash.

**Comment by StFS** [comment]
For fun I tried a quick and dirty implementation of Jackson and it didn't improve the speed at all. Maybe there is one that would be faster but I'm not all that familiar with different JSON parsers so I'm open to suggestions to try out.

**Comment by StFS** [comment]
However, I do think that profiling the code would be the best thing to do to actually see what's going on.

**Comment by lusis** [comment]
@spredzy can you paste your log4j configuration? That jstack sadly looks like standard log4j appender blocking. CallAppenders has a big synchronized lock around it that you hit regardless of logging level.

If I can see your configuration it might prove. (or disprove my theory)

**Comment by Spredzy** [comment]
@lusis That it what my original  log4j conf looks like (slow)

```
<appender name="PENTAHOFILE" class="org.apache.log4j.DailyRollingFileAppender">
    <param name="File" value="/var/log/pentaho/pentaho_dev.log"/>
    <param name="Append" value="false"/>
    <param name="Threshold" value="WARN"/>
    <param name="DatePattern" value="'.'yyyy-MM-dd"/>
    <layout class="net.logstash.log4j.JSONEventLayout"/>
</appender>
```

After using a AsyncAppender application seems back to original speed, this is my new log4j.xml conf

```
<root>
    <appender-ref ref="ASYNC"/>
</root>

<appender name="ASYNC" class="org.apache.log4j.AsyncAppender">
    <appender-ref ref="PENTAHOFILE"/>
</appender>

<appender name="PENTAHOFILE" class="org.apache.log4j.DailyRollingFileAppender">
    <param name="File" value="/var/log/pentaho/pentaho_dev.log"/>
    <param name="Append" value="false"/>
    <param name="Threshold" value="WARN"/>
    <param name="DatePattern" value="'.'yyyy-MM-dd"/>
    <layout class="net.logstash.log4j.JSONEventLayout"/>
</appender>
```

**Comment by StFS** [comment]
and even faster would be to turn off location info in the layout if you don't need it (it's on in your current setup).

**Comment by Spredzy** [comment]
Actually I changed it in the JSONEventLayout.java file and set location to false there (I recompiled it and dropped it in my lib/ folder), so AsyncAppender + Location turned to false is a big win performance wise.

**Comment by StFS** [comment]
Ok. FYI, you know you don't need to recompile to turn locationInfo off. I don't know how it's done in XML config but you can see a properties config file here that does it:
https://github.com/logstash/log4j-jsonevent-layout/blob/master/src/main/resources/log4j.locinfo.properties.example

I think you'd do it like this:

``` xml
<appender name="PENTAHOFILE" class="org.apache.log4j.DailyRollingFileAppender">
    <param name="File" value="/var/log/pentaho/pentaho_dev.log"/>
    <param name="Append" value="false"/>
    <param name="Threshold" value="WARN"/>
    <param name="DatePattern" value="'.'yyyy-MM-dd"/>
    <layout class="net.logstash.log4j.JSONEventLayout">
        <param name="locationInfo" value="false"/>
    </layout>
</appender>
```

**Comment by Spredzy** [comment]
I found the source of my error.

I've made my test in a Vagrant created box and I did not edit the `/etc/hosts` file to add my actual `ip HOSTNAME` line, which provoked the call to `hostname = new HostData().getHostName();` to take up to 5 sec it was probably throwing an error internally. Once I edited the `/etc/hosts` file, the JSONEventLayout take only few millisecond, here the result of `mvn clean install`

```
Running net.logstash.log4j.JSONEventLayoutTest

Beginning : 2013-03-09T03:58:14.702-0800
End : 2013-03-09T03:58:14.713-0800

Beginning : 2013-03-09T03:58:14.735-0800
End : 2013-03-09T03:58:14.735-0800

Beginning : 2013-03-09T03:58:14.737-0800
End : 2013-03-09T03:58:14.737-0800

Beginning : 2013-03-09T03:58:14.739-0800
End : 2013-03-09T03:58:14.739-0800

Beginning : 2013-03-09T03:58:14.740-0800
End : 2013-03-09T03:58:14.746-0800

Beginning : 2013-03-09T03:58:14.753-0800
End : 2013-03-09T03:58:14.753-0800

Beginning : 2013-03-09T03:58:14.754-0800
End : 2013-03-09T03:58:14.754-0800

Beginning : 2013-03-09T03:58:14.755-0800
End : 2013-03-09T03:58:14.756-0800

Tests run: 9, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.09 sec
```

@StFS I have locationInfo set to true here

@lusis It's working fast without using AsyncAppender also

I think that discards the JSON parser being to slow

**Comment by lusis** [comment]
Oh shit. That's not good. I didn't set a timeout I don't think. Just a fallback if not detected.  So amateur. Sorry about that. Ill get a fix in tonight.

**Comment by looztra** [comment]
Is it me or the hostname is requested for each call to the _format_ method? Maybe a single call during constructor call would be sufficient, no?

**Comment by jkoppe** [comment]
Looks like looztra committed 3c5cc9ed1a which moved the hostname call to the constructor method.

@StFS: How difficult was the Jackson replacement.  We use Jackson here, so we'd want to swap minidev out for Jackson.

I'm very interested in deploying this Layout in production, but this issue has got me nervous :) Should we be using the AsyncAppender in production or should everything be OK at this point?

**Comment by Spredzy** [comment]
@jkoppe This issue is not a real issue, it was just a misconfiguration from my part. If you get your `/etc/hosts` correctly configure you're all good. I use this on all my production tomcat servers :)

**Comment by StFS** [comment]
Hi @jkoppe.

The Jackson replacement was trivial... I'll see if I have it and maybe even create a branch with that for you. However, I did not spend any efffort testing it and making sure it worked well (other than running the unit tests).

-Stefan Freyr.

**Comment by StFS** [comment]
@jkoppe I just pushed a fasterxml branch with my (very crude) implementation of using Jackson).

Please note that this is very untested and if I recall correctly, the performance of Jackson was worse than the current one.

You can see the diff between the two here: https://github.com/logstash/log4j-jsonevent-layout/compare/fasterxml

@lusis I hope you don't mind me creating that branch. It shouldn't be used for anything though (since it's untested) and maybe I should have made a fork instead... I'm not too familiar with the "correct" workflows here. Apologies if this is stepping on any toes. Anyway, the branch can be deleted as soon as @jkoppe has had a chance to grab the code and create a fork from it if he wants.

**Comment by jkoppe** [comment]
I've copied the branch to my machine -- thanks!

**Comment by StFS** [comment]
ok, just make sure that you have the latest version... I did the initial push but then I figured out that I hadn't merged the latest changes from the master branch. So just do a quick pull and let me know and then I'll delete the branch.

**Comment by jkoppe** [comment]
i forked, pulled your branch which had two commits, and pushed that into my backup server :)  you're safe to delete the branch.

**Comment by electrical** [comment]
I think this issue can be closed?

**Comment by lusis** [comment]
Yeah I'm pretty sure this is good to close. I still want to work in some perf tests into the test suite to ensure that we maintain a good performance profile but things are good for now.
